### ISSUE TITLE
errors at build with Node 12.8.1 (Electron 7.1.9)

### ISSUE THREAD

**Issue by tripower** [joeferner/node-java#493]
Hello

would it be possible to fix this errors?

..\src\java.cpp(206): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(234): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\javaObject.cpp(32): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\javaObject.cpp(32): error C2228: left of '.As' must have class/struct/union [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\javaObject.cpp(32): error C2059: syntax error: ')' [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\javaObject.cpp(33): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(278): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(335): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(335): error C2661: 'v8ToJava': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(772): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(786): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(408): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(800): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(408): error C2661: 'v8ToJava': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(814): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(828): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(842): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(455): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(856): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(880): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(642): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(652): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(715): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(1254): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\java.cpp(1278): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [..elec7\node_modules\java\build\nodejavabridge_bindings.vcxproj]

thanks in advance

**Comment by tripower** [comment]
so, I have locally made some changes 
the build works and looks not so bad, but I'm no cpp developer so maybe can verify if this is right
and it would be fine if a separat version for Node 12.8.1 can be made

for example:
from 
v8::Local<v8::Object> asyncOptions = java->handle()->Get(Nan::New<v8::String>("asyncOptions").ToLocalChecked())**.As<v8::Object>();**
to
v8::Local<v8::Object> asyncOptions = **v8::Local<v8::Object>::Cast**(java->handle()->Get(**Nan::GetCurrentContext()**, Nan::New<v8::String>("asyncOptions").ToLocalChecked()).ToLocalChecked());

**Comment by joeferner** [comment]
I have a branch starting down the path of support Node 12 but I ran into some issues I can't get past https://github.com/joeferner/node-java/tree/node12 . The first step is upgrading NaN to the latest version. NaN will isolate any of the changes between different versions of Node so no differing versions should be needed..

**Comment by stevenpkg** [comment]
Any news on support for node v12?
