### ISSUE TITLE
New Typescript bindings appear to contain errors

### ISSUE THREAD

**Issue by lm-sousa** [joeferner/node-java#615]
The new Typescript bindings introduced in https://github.com/joeferner/node-java/pull/613 and released with `0.16.0` seem to contain some errors.

```
../../node_modules/java/java.d.ts:4:13 - error TS2502: 'NodeJavaCore' is referenced directly or indirectly in its own type annotation.
4 declare var NodeJavaCore: NodeJavaCore.NodeAPI;
              ~~~~~~~~~~~~
../../node_modules/java/java.d.ts:4:40 - error TS2694: Namespace 'NodeJavaCore' has no exported member 'NodeAPI'.
4 declare var NodeJavaCore: NodeJavaCore.NodeAPI;
                                         ~~~~~~~
../../node_modules/java/java.d.ts:4:13 - error TS2502: 'NodeJavaCore' is referenced directly or indirectly in its own type annotation.
4 declare var NodeJavaCore: NodeJavaCore.NodeAPI;
              ~~~~~~~~~~~~
../../node_modules/java/java.d.ts:4:40 - error TS2694: Namespace 'NodeJavaCore' has no exported member 'NodeAPI'.
4 declare var NodeJavaCore: NodeJavaCore.NodeAPI;
                                         ~~~~~~~
```

This is the error log when trying to compile my TS sources in a package that has `java@0.16.0` as a dependency.

**Comment by lm-sousa** [comment]
It seems that: 

```typescript
declare var NodeJavaCore: NodeJavaCore.NodeAPI;
```
should become: 

```typescript
declare var NodeJavaCore: NodeJavaCore.Java;
```

**Comment by joeferner** [comment]
I tried reproducing the error with `examples/lucene` but couldn't manage to reproduce. But I agree it should be `declare var NodeJavaCore: NodeJavaCore.Java;`

Published 0.16.1, can you give that a try.
