### ISSUE TITLE
"npm install java" do not work on java "1.7.0_04" ?

### ISSUE THREAD

**Issue by achenzhaoa** [joeferner/node-java#10]
Hi,

My java is jdk1.7.0_04. When I run "npm install java",it did failed.

hyjy@hyjy-Latitude-E6400:~/workspace/testnodejava$ java -version
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b20)
Java HotSpot(TM) Server VM (build 23.0-b21, mixed mode)

hyjy@hyjy-Latitude-E6400:~/workspace/testnodejava$ npm install mnm
npm http GET https://registry.npmjs.org/mnm
npm http 304 https://registry.npmjs.org/mnm
mnm@0.0.4 ./node_modules/mnm
hyjy@hyjy-Latitude-E6400:~/workspace/testnodejava$ npm install java
npm http GET https://registry.npmjs.org/java
npm http 304 https://registry.npmjs.org/java

> java@0.0.4 install /home/hyjy/workspace/testnodejava/node_modules/java
> node mnm.js build

[1/6] cxx: src/nodeJavaBridge.cpp -> build/Release/src/nodeJavaBridge.o
In file included from /home/hyjy/workspace/testnodejava/node_modules/java/src/nodeJavaBridge.cpp:2:0:
/home/hyjy/workspace/testnodejava/node_modules/java/src/java.h:6:18: fatal error: node.h: No such file or directory
compilation terminated.
[2/6] cxx: src/java.cpp -> build/Release/src/java.o
In file included from /home/hyjy/workspace/testnodejava/node_modules/java/src/java.cpp:2:0:
/home/hyjy/workspace/testnodejava/node_modules/java/src/java.h:6:18: fatal error: node.h: No such file or directory
compilation terminated.
[3/6] cxx: src/utils.cpp -> build/Release/src/utils.o
In file included from /home/hyjy/workspace/testnodejava/node_modules/java/src/utils.cpp:2:0:
/home/hyjy/workspace/testnodejava/node_modules/java/src/utils.h:11:16: fatal error: uv.h: No such file or directory
compilation terminated.
[4/6] cxx: src/javaObject.cpp -> build/Release/src/javaObject.o
In file included from /home/hyjy/workspace/testnodejava/node_modules/java/src/javaObject.cpp:2:0:
/home/hyjy/workspace/testnodejava/node_modules/java/src/javaObject.h:6:18: fatal error: node.h: No such file or directory
compilation terminated.
[5/6] cxx: src/methodCallBaton.cpp -> build/Release/src/methodCallBaton.o
In file included from /home/hyjy/workspace/testnodejava/node_modules/java/src/methodCallBaton.h:5:0,
                 from /home/hyjy/workspace/testnodejava/node_modules/java/src/methodCallBaton.cpp:2:
/home/hyjy/workspace/testnodejava/node_modules/java/src/utils.h:11:16: fatal error: uv.h: No such file or directory
compilation terminated.
ERROR: [Error: At least one file failed to compile.]
npm ERR! error installing java@0.0.4

npm ERR! java@0.0.4 install: `node mnm.js build`
npm ERR! `sh "-c" "node mnm.js build"` failed with 1
npm ERR! 
npm ERR! Failed at the java@0.0.4 install script.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node mnm.js build
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.2.0-25-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "java"
npm ERR! cwd /home/hyjy/workspace/testnodejava
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message java@0.0.4 install: `node mnm.js build`
npm ERR! message `sh "-c" "node mnm.js build"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hyjy/workspace/testnodejava/npm-debug.log
npm not ok

Please advice

Chen Zhao
